# Generated by scripts/gen_models.py from spec/consultas-externas.resolved.json.
# Do not edit by hand: change the overlay in spec/ and run `make models`.

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, Field


class Sorting(Enum):
    ASC = "ASC"
    DESC = "DESC"


class Order(Enum):
    ASC = "ASC"
    DESC = "DESC"


class PaginationBuilder(BaseModel):
    sorting: Annotated[
        dict[str, Sorting] | None,
        Field(
            description="Map of column name to ASC/DESC. Sending an array is rejected with a Jackson deserialization error."
        ),
    ] = None
    page: Annotated[
        int | None,
        Field(
            description='1-based page number. page=0 fails with "Page index must not be less than zero!". Responses are Spring Page objects and report the page 0-based in `number` / `pageable.pageNumber`.',
            ge=1,
        ),
    ] = None
    size: Annotated[int | None, Field(ge=1)] = None
    column: str | None = None
    order: Order | None = None
    filter: Annotated[
        dict[str, dict[str, Any]] | None,
        Field(
            description="Map of filter key to value. Required keys depend on the endpoint; see each operation's `x-required-filters`."
        ),
    ] = None


class Sort(BaseModel):
    sorted: bool | None = None
    empty: bool | None = None
    unsorted: bool | None = None


class Estagio(Enum):
    DESBLOQUEADO = "DESBLOQUEADO"
    NAO_PUBLICADO = "NAO_PUBLICADO"
    EM_CARENCIA = "EM_CARENCIA"
    CONSOLIDADO = "CONSOLIDADO"


class UdiDTO(BaseModel):
    id: int | None = None
    udiDi: str | None = None
    nomeComercial: str | None = None
    razaoSocialFabLegal: str | None = None
    termoGmdn: str | None = None
    cnpjDetentora: str | None = None
    razaoSocialDetentora: str | None = None
    dtPublicacao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    desbloqueado: Annotated[
        str | None,
        Field(
            description='Observed value: "N" (the detail endpoint uses SIM/NAO for the same flag).'
        ),
    ] = None
    estagio: Estagio | None = None


class Ativo(Enum):
    SIM = "SIM"
    NAO = "NAO"


class TermoGMDNDTO(BaseModel):
    codigo: str | None = None
    nome: str | None = None
    definicao: str | None = None
    nomeOriginal: str | None = None
    definicaoOriginal: str | None = None
    ativo: Ativo | None = None


class NomeTecnicoDTO(BaseModel):
    codigo: str | None = None
    nomeTecnico: str | None = None
    descricao: str | None = None
    tipoProduto: int | None = None
    descricaoTipoProduto: str | None = None
    classeRisco: str | None = None
    dataAtualizacao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None


class FilaCalculadaDTO(BaseModel):
    nuOrdem: Annotated[
        int | None, Field(description="Position in the queue (1 = next).")
    ] = None
    dtEntrada: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    nuExpediente: str | None = None
    codAssunto: str | None = None
    dsAssunto: str | None = None
    nuProcesso: str | None = None
    dtGeracaoFila: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    numeroProcessoFormatado: str | None = None
    expeditenteFormatado: str | None = None


class Sistema(BaseModel):
    codigoAssunto: int | None = None
    codigoSistema: str | None = None
    nome: str | None = None
    bloqueado: str | None = None
    hiperlink: str | None = None


class TipoProduto(BaseModel):
    id: int | None = None
    descricao: str | None = None


class ConsultaFuncionamento(BaseModel):
    ordem: int | None = None
    cnpj: str | None = None
    razaoSocial: str | None = None
    nomeFantasia: str | None = None
    autorizacao: str | None = None
    novaAutorizacao: str | None = None
    numeroProcesso: str | None = None
    tipoProduto: str | None = None
    enderecoInternet: str | None = None
    numeroSac: str | None = None
    dataAutorizacao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    dataAtualizacao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    cadastro: bool | None = None
    ativa: bool | None = None


class DI(BaseModel):
    id: str | None = None
    entidadeEmissora: str | None = None


class DetalheEmpresaDTO(BaseModel):
    razaoSocial: str | None = None
    endereco: str | None = None
    pais: str | None = None


class IsUsoUnico(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsPassivelReutilizacao(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsSemLimitePredefinido(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsDispositivoEsteril(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsRequerEsterilizacao(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsPossuiLatex(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsUsoLeigo(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsDispositivoCombinado(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsMaterialBiologico(Enum):
    SIM = "SIM"
    NAO = "NAO"


class IsIncorporaIA(Enum):
    SIM = "SIM"
    NAO = "NAO"


class HasIdentificadorUnidadeUtilizacao(Enum):
    SIM = "SIM"
    NAO = "NAO"


class HasNumeroLote(Enum):
    SIM = "SIM"
    NAO = "NAO"


class HasNumeroSerie(Enum):
    SIM = "SIM"
    NAO = "NAO"


class HasDtValidade(Enum):
    SIM = "SIM"
    NAO = "NAO"


class HasDtManufRecondReproc(Enum):
    SIM = "SIM"
    NAO = "NAO"


class HasDtLiberacaoSAMD(Enum):
    SIM = "SIM"
    NAO = "NAO"


class HasVersaoSoftware(Enum):
    SIM = "SIM"
    NAO = "NAO"


class Desbloqueado(Enum):
    SIM = "SIM"
    NAO = "NAO"


class EmbalagemDTO(BaseModel):
    udiDi: DI | None = None
    nivelEmbalagem: int | None = None
    qtdPorEmbalagem: int | None = None


class HistoricoIdDTO(BaseModel):
    idHistorico: int | None = None
    idEntity: int | None = None


class RegistroProdutoDTO(BaseModel):
    numeroRegistro: str | None = None
    nomeProduto: str | None = None
    tipoProduto: int | None = None
    dtVencimento: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    dtCancelamento: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    nuCnpjEmpresa: str | None = None
    razaoSocialEmpresa: str | None = None
    enderecoEmpresa: str | None = None
    nomeTecnico: str | None = None
    classeRisco: str | None = None


class RegistroProdutoView(BaseModel):
    numeroRegistro: str | None = None
    nomeProduto: str | None = None
    tipoProduto: int | None = None
    dtVencimento: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    dtCancelamento: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    nuCnpjEmpresa: str | None = None
    razaoSocialEmpresa: str | None = None
    enderecoEmpresa: str | None = None
    nomeTecnico: str | None = None
    classeRisco: str | None = None


class VersaoDispositivoDTO(BaseModel):
    id: HistoricoIdDTO | None = None
    codigoUdiDi: str | None = None
    codigoVersao: str | None = None
    dtVersao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    numeroVersao: int | None = None


class HistoricoUdiDTO(BaseModel):
    id: int | None = None
    tipoHistorico: str | None = None
    totalRegistros: int | None = None
    dtInicio: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    dtFim: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    dtGeracao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None


class ChaveValorInteger(BaseModel):
    descricao: str | None = None
    id: int | None = None


class ChaveValorLong(BaseModel):
    descricao: str | None = None
    id: int | None = None


class DocumentacaoRequerida(BaseModel):
    numeroOrdem: int | None = None
    descricaoItemChecklist: str | None = None


class Conteudo(BaseModel):
    binaryStream: dict[str, Any] | None = None


class Formulario(BaseModel):
    id: int | None = None
    nome: str | None = None
    nomeArquivo: str | None = None
    tipoArquivo: str | None = None
    conteudo: Conteudo | None = None


class Servico(BaseModel):
    codigoServico: int | None = None
    descricao: str | None = None
    hiperlink: str | None = None


class ValorTaxaEmbarcacaoFilho(BaseModel):
    classe: str | None = None
    valorTaxa: str | None = None


class ValorTaxaEmpresa(BaseModel):
    codigoAssunto: int | None = None
    codigoFatoGerador: str | None = None
    porte: str | None = None
    valorTaxa: str | None = None


class TipoSolicitacaoDTO(BaseModel):
    nome: str | None = None
    valor: str | None = None


class TipoProdutoDTO(BaseModel):
    id: int | None = None
    descricao: str | None = None


class SistemaDTO(BaseModel):
    id: str | None = None
    nome: str | None = None


class ServicoDTO(BaseModel):
    id: int | None = None
    descricao: str | None = None
    hiperlink: str | None = None


class AssuntoDTO(BaseModel):
    id: int | None = None
    descricao: str | None = None


class ErroApi(BaseModel):
    """
    Envelope returned with HTTP 500 for both internal errors and request validation failures (missing required filter, page < 1, malformed body).
    """

    status: Annotated[str | None, Field(examples=["INTERNAL_SERVER_ERROR"])] = None
    mensagem: Annotated[
        str | None,
        Field(
            description="Human message, or an unresolved i18n key such as `mensagens.MSG-062` (= at least one filter is required)."
        ),
    ] = None
    data_hora: Annotated[
        list[int] | None,
        Field(
            description="Server-local timestamp as [year, month, day, hour, minute, second, nanosecond].",
            max_length=7,
            min_length=7,
        ),
    ] = None
    mensagem_detalhada: Annotated[
        str | None,
        Field(
            description="Detail text, e.g. \"Filtro 'subfila' não informado.\" or a Java stack message."
        ),
    ] = None


class PageableObject(BaseModel):
    paged: bool | None = None
    unpaged: bool | None = None
    pageNumber: int | None = None
    pageSize: int | None = None
    offset: int | None = None
    sort: Sort | None = None


class PageTermoGMDNDTO(BaseModel):
    totalPages: int | None = None
    totalElements: int | None = None
    number: int | None = None
    size: int | None = None
    numberOfElements: int | None = None
    content: list[TermoGMDNDTO] | None = None
    sort: Sort | None = None
    first: bool | None = None
    last: bool | None = None
    pageable: PageableObject | None = None
    empty: bool | None = None


class PageNomeTecnicoDTO(BaseModel):
    totalPages: int | None = None
    totalElements: int | None = None
    number: int | None = None
    size: int | None = None
    numberOfElements: int | None = None
    content: list[NomeTecnicoDTO] | None = None
    sort: Sort | None = None
    first: bool | None = None
    last: bool | None = None
    pageable: PageableObject | None = None
    empty: bool | None = None


class ConsultaAssunto(BaseModel):
    idAssunto: int | None = None
    descricao: str | None = None
    tipoSolicitacao: str | None = None
    tipoProduto: TipoProduto | None = None
    sistemas: list[Sistema] | None = None
    fatoGerador: str | None = None


class PageConsultaAssunto(BaseModel):
    totalPages: int | None = None
    totalElements: int | None = None
    number: int | None = None
    size: int | None = None
    numberOfElements: int | None = None
    content: list[ConsultaAssunto] | None = None
    sort: Sort | None = None
    first: bool | None = None
    last: bool | None = None
    pageable: PageableObject | None = None
    empty: bool | None = None


class DispositivoDTO(BaseModel):
    id: int | None = None
    udiDi: DI | None = None
    udiDiOriginal: DI | None = None
    registroProduto: RegistroProdutoDTO | None = None
    tipoProduto: str | None = None
    recondicionadora: DetalheEmpresaDTO | None = None
    nomeComercial: str | None = None
    versaoModelo: str | None = None
    codigoCatalogo: str | None = None
    fabricanteLegal: DetalheEmpresaDTO | None = None
    qtdPorEmbalagem: int | None = None
    categoria: str | None = None
    isUsoUnico: IsUsoUnico | None = None
    isPassivelReutilizacao: IsPassivelReutilizacao | None = None
    isSemLimitePredefinido: IsSemLimitePredefinido | None = None
    qtdMaxReutilizacoes: int | None = None
    isDispositivoEsteril: IsDispositivoEsteril | None = None
    isRequerEsterilizacao: IsRequerEsterilizacao | None = None
    isPossuiLatex: IsPossuiLatex | None = None
    isUsoLeigo: IsUsoLeigo | None = None
    isDispositivoCombinado: IsDispositivoCombinado | None = None
    isMaterialBiologico: IsMaterialBiologico | None = None
    isIncorporaIA: IsIncorporaIA | None = None
    compatibilidadeComRM: str | None = None
    contraindicacoesCriticas: str | None = None
    condicoesArmazenamentoManuseio: str | None = None
    caracteristicasDimensionais: str | None = None
    termoGmdn: TermoGMDNDTO | None = None
    hasIdentificadorUnidadeUtilizacao: HasIdentificadorUnidadeUtilizacao | None = None
    descIdentificadorUnidadeUtilizacao: str | None = None
    hasNumeroLote: HasNumeroLote | None = None
    hasNumeroSerie: HasNumeroSerie | None = None
    hasDtValidade: HasDtValidade | None = None
    hasDtManufRecondReproc: HasDtManufRecondReproc | None = None
    hasDtLiberacaoSAMD: HasDtLiberacaoSAMD | None = None
    hasVersaoSoftware: HasVersaoSoftware | None = None
    informacoesSuplementares: str | None = None
    informacoesAtendimentoConsumidor: str | None = None
    dtDescontinuacao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    dtPublicacao: Annotated[
        AwareDatetime | None,
        Field(
            description="Sent as integer epoch milliseconds (midnight America/Sao_Paulo for date-only values)."
        ),
    ] = None
    ativo: Ativo | None = None
    desbloqueado: Desbloqueado | None = None
    codigoVersao: str | None = None
    nomeProdutoRegularizacao: str | None = None
    embalagens: list[EmbalagemDTO] | None = None
    metodosEsterilizacao: list[str] | None = None


class DispositivoIdDTO(BaseModel):
    id: int | None = None
    udiDi: str | None = None
    udiDiEmissora: str | None = None
    idDispositivoPrevio: int | None = None
    tipoSucessao: str | None = None
    registroProduto: RegistroProdutoView | None = None


class SucessaoDispositivoDTO(BaseModel):
    previo: DispositivoIdDTO | None = None
    sucessor: DispositivoIdDTO | None = None


class ValorTaxaEmbarcacao(BaseModel):
    codigoAssunto: int | None = None
    classe: str | None = None
    valorTaxa: str | None = None
    valorTaxaEmbarcacaoFilhos: list[ValorTaxaEmbarcacaoFilho] | None = None


class PageUdiDTO(BaseModel):
    totalPages: int | None = None
    totalElements: int | None = None
    number: int | None = None
    size: int | None = None
    numberOfElements: int | None = None
    content: list[UdiDTO] | None = None
    sort: Sort | None = None
    first: bool | None = None
    last: bool | None = None
    pageable: PageableObject | None = None
    empty: bool | None = None


class DetalheDispositivoDTO(BaseModel):
    dispositivo: DispositivoDTO | None = None
    autorizacaoFuncionamento: ConsultaFuncionamento | None = None
    versoes: list[VersaoDispositivoDTO] | None = None
    versaoDetalhada: VersaoDispositivoDTO | None = None
    sucessao: SucessaoDispositivoDTO | None = None
    estagio: Estagio | None = None


class DetalheAssunto(BaseModel):
    idAssunto: int | None = None
    descricao: str | None = None
    tipoSolicitacao: str | None = None
    tipoProduto: TipoProduto | None = None
    sistemas: list[Sistema] | None = None
    fatoGerador: str | None = None
    assunto: str | None = None
    servicos: list[Servico] | None = None
    formularios: list[Formulario] | None = None
    documentosRequeridos: list[DocumentacaoRequerida] | None = None
    fundamentacaoLegal: str | None = None
    valoresTaxaEmpresa: list[ValorTaxaEmpresa] | None = None
    valoresTaxaEmbarcacao: list[ValorTaxaEmbarcacao] | None = None
