#!/usr/bin/env python3
"""Regenerate src/anvisa/models.py from spec/consultas-externas.resolved.json.

Run from packages/python:  uv run python scripts/gen_models.py   (or `make models` at the root)
Only `components.schemas` are generated; the runtime (auth, throttle, client) is hand-written.
"""

from pathlib import Path

from datamodel_code_generator import (
    DataModelType,
    InputFileType,
    OpenAPIScope,
    PythonVersion,
    generate,
)
from datamodel_code_generator.format import Formatter

HERE = Path(__file__).resolve().parent.parent
SPEC = HERE.parent.parent / "spec" / "consultas-externas.resolved.json"
OUT = HERE / "src" / "anvisa" / "models.py"

generate(
    SPEC,
    input_file_type=InputFileType.OpenAPI,
    input_filename=SPEC.name,
    output=OUT,
    output_model_type=DataModelType.PydanticV2BaseModel,
    openapi_scopes=[OpenAPIScope.Schemas],
    target_python_version=PythonVersion.PY_310,
    use_standard_collections=True,
    use_union_operator=True,
    use_annotated=True,
    field_constraints=True,
    use_schema_description=True,
    use_double_quotes=True,
    collapse_root_models=True,
    disable_timestamp=True,
    formatters=[Formatter.BLACK, Formatter.ISORT],
    custom_file_header=(
        "# Generated by scripts/gen_models.py from spec/consultas-externas.resolved.json.\n"
        "# Do not edit by hand: change the overlay in spec/ and run `make models`."
    ),
)
# datamodel-codegen writes with the platform newline; the repo (and CI's drift check) expect LF
OUT.write_bytes(OUT.read_bytes().replace(b"\r\n", b"\n"))
print(f"wrote {OUT.relative_to(HERE)}")
